### ISSUE TITLE
Wrong dependencies on v1.0.0

### ISSUE THREAD

**Issue by fredericvl** [opendistro-for-elasticsearch/opendistro-build#91] opened 2019-07-01 13:50 UTC
Currently I have a cluster running of 3 nodes on OpenDistro v0.9.0.
Today I have tried to upgrade to v1.0.0 but without success.
It looks like the wrong dependencies are set on the v1.0.0 package.
It wants to update the security & sql package to 1.1 and they have a requirement of ES 7.1.1 which is conflicting with version 7.0.1 it should be.

This is the output when I try to upgrade:
<pre>
# yum install opendistroforelasticsearch-1.0.0
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.netcologne.de
 * epel: mirror.de.leaseweb.net
 * extras: mirror.23media.com
 * updates: mirror.23media.com
Resolving Dependencies
--> Running transaction check
---> Package opendistroforelasticsearch.noarch 0:0.9.0-1 will be updated
---> Package opendistroforelasticsearch.noarch 0:1.0.0-1 will be an update
--> Processing Dependency: elasticsearch-oss = 7.0.1 for package: opendistroforelasticsearch-1.0.0-1.noarch
--> Processing Dependency: opendistro-job-scheduler < 1.0.1 for package: opendistroforelasticsearch-1.0.0-1.noarch
--> Processing Dependency: opendistro-sql >= 1.0.0 for package: opendistroforelasticsearch-1.0.0-1.noarch
--> Processing Dependency: opendistro-security >= 1.0.0 for package: opendistroforelasticsearch-1.0.0-1.noarch
--> Processing Dependency: opendistro-performance-analyzer >= 1.0.0 for package: opendistroforelasticsearch-1.0.0-1.noarch
--> Processing Dependency: opendistro-job-scheduler >= 1.0.0 for package: opendistroforelasticsearch-1.0.0-1.noarch
--> Processing Dependency: opendistro-alerting >= 1.0.0 for package: opendistroforelasticsearch-1.0.0-1.noarch
--> Running transaction check
---> Package opendistro-alerting.noarch 0:0.9.0.0-1 will be updated
---> Package opendistro-alerting.noarch 0:1.0.0.0-1 will be an update
--> Processing Dependency: elasticsearch-oss = 7.0.1 for package: opendistro-alerting-1.0.0.0-1.noarch
---> Package opendistro-job-scheduler.noarch 0:1.0.0.0-1 will be installed
--> Processing Dependency: elasticsearch-oss = 7.0.1 for package: opendistro-job-scheduler-1.0.0.0-1.noarch
---> Package opendistro-performance-analyzer.noarch 0:0.9.0.0-1 will be updated
---> Package opendistro-performance-analyzer.noarch 0:1.0.0.0-1 will be an update
--> Processing Dependency: elasticsearch-oss = 7.0.1 for package: opendistro-performance-analyzer-1.0.0.0-1.noarch
---> Package opendistro-security.noarch 0:0.9.0.0-0 will be updated
--> Processing Dependency: opendistro-security < 1.0.1 for package: opendistroforelasticsearch-1.0.0-1.noarch
---> <b>Package opendistro-security.noarch 0:1.1.0.0-0 will be an update</b>
--> <b>Processing Dependency: elasticsearch-oss = 7.1.1 for package: opendistro-security-1.1.0.0-0.noarch</b>
---> Package opendistro-sql.noarch 0:0.9.0.0-1 will be updated
--> Processing Dependency: opendistro-sql < 1.0.1 for package: opendistroforelasticsearch-1.0.0-1.noarch
---> <b>Package opendistro-sql.noarch 0:1.1.0.0-1 will be an update</b>
--> <b>Processing Dependency: elasticsearch-oss = 7.1.1 for package: opendistro-sql-1.1.0.0-1.noarch</b>
---> Package opendistroforelasticsearch.noarch 0:1.0.0-1 will be an update
--> Processing Dependency: elasticsearch-oss = 7.0.1 for package: opendistroforelasticsearch-1.0.0-1.noarch
--> Processing Dependency: opendistro-sql < 1.0.1 for package: opendistroforelasticsearch-1.0.0-1.noarch
--> Processing Dependency: opendistro-security < 1.0.1 for package: opendistroforelasticsearch-1.0.0-1.noarch
--> Finished Dependency Resolution
Error: Package: opendistro-performance-analyzer-1.0.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
           Requires: elasticsearch-oss = 7.0.1
           Installed: elasticsearch-oss-6.7.1-1.noarch (@elasticsearch-6.x)
               elasticsearch-oss = 6.7.1-1
           Available: elasticsearch-oss-6.3.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.0-1
           Available: elasticsearch-oss-6.3.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.1-1
           Available: elasticsearch-oss-6.3.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.2-1
           Available: elasticsearch-oss-6.4.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.0-1
           Available: elasticsearch-oss-6.4.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.1-1
           Available: elasticsearch-oss-6.4.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.2-1
           Available: elasticsearch-oss-6.4.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.3-1
           Available: elasticsearch-oss-6.5.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.0-1
           Available: elasticsearch-oss-6.5.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.1-1
           Available: elasticsearch-oss-6.5.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.2-1
           Available: elasticsearch-oss-6.5.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.3-1
           Available: elasticsearch-oss-6.5.4-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.4-1
           Available: elasticsearch-oss-6.6.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.0-1
           Available: elasticsearch-oss-6.6.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.1-1
           Available: elasticsearch-oss-6.6.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.2-1
           Available: elasticsearch-oss-6.7.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.0-1
           Available: elasticsearch-oss-6.7.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.2-1
           Available: elasticsearch-oss-6.8.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.0-1
           Available: elasticsearch-oss-6.8.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.1-1
           Available: elasticsearch-oss-7.0.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.0-1
           Available: elasticsearch-oss-7.0.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.1-1
           Available: elasticsearch-oss-7.1.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.0-1
           Available: elasticsearch-oss-7.1.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.1-1
           Available: elasticsearch-oss-7.2.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.2.0-1
<b>Error: Package: opendistro-security-1.1.0.0-0.noarch (opendistroforelasticsearch-artifacts-repo)
           Requires: elasticsearch-oss = 7.1.1</b>
           Installed: elasticsearch-oss-6.7.1-1.noarch (@elasticsearch-6.x)
               elasticsearch-oss = 6.7.1-1
           Available: elasticsearch-oss-6.3.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.0-1
           Available: elasticsearch-oss-6.3.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.1-1
           Available: elasticsearch-oss-6.3.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.2-1
           Available: elasticsearch-oss-6.4.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.0-1
           Available: elasticsearch-oss-6.4.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.1-1
           Available: elasticsearch-oss-6.4.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.2-1
           Available: elasticsearch-oss-6.4.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.3-1
           Available: elasticsearch-oss-6.5.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.0-1
           Available: elasticsearch-oss-6.5.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.1-1
           Available: elasticsearch-oss-6.5.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.2-1
           Available: elasticsearch-oss-6.5.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.3-1
           Available: elasticsearch-oss-6.5.4-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.4-1
           Available: elasticsearch-oss-6.6.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.0-1
           Available: elasticsearch-oss-6.6.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.1-1
           Available: elasticsearch-oss-6.6.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.2-1
           Available: elasticsearch-oss-6.7.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.0-1
           Available: elasticsearch-oss-6.7.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.2-1
           Available: elasticsearch-oss-6.8.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.0-1
           Available: elasticsearch-oss-6.8.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.1-1
           Available: elasticsearch-oss-7.0.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.0-1
           Available: elasticsearch-oss-7.0.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.1-1
           Available: elasticsearch-oss-7.1.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.0-1
           Available: elasticsearch-oss-7.1.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.1-1
           Available: elasticsearch-oss-7.2.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.2.0-1
<b>Error: Package: opendistro-sql-1.1.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
           Requires: elasticsearch-oss = 7.1.1</b>
           Installed: elasticsearch-oss-6.7.1-1.noarch (@elasticsearch-6.x)
               elasticsearch-oss = 6.7.1-1
           Available: elasticsearch-oss-6.3.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.0-1
           Available: elasticsearch-oss-6.3.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.1-1
           Available: elasticsearch-oss-6.3.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.2-1
           Available: elasticsearch-oss-6.4.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.0-1
           Available: elasticsearch-oss-6.4.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.1-1
           Available: elasticsearch-oss-6.4.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.2-1
           Available: elasticsearch-oss-6.4.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.3-1
           Available: elasticsearch-oss-6.5.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.0-1
           Available: elasticsearch-oss-6.5.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.1-1
           Available: elasticsearch-oss-6.5.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.2-1
           Available: elasticsearch-oss-6.5.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.3-1
           Available: elasticsearch-oss-6.5.4-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.4-1
           Available: elasticsearch-oss-6.6.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.0-1
           Available: elasticsearch-oss-6.6.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.1-1
           Available: elasticsearch-oss-6.6.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.2-1
           Available: elasticsearch-oss-6.7.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.0-1
           Available: elasticsearch-oss-6.7.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.2-1
           Available: elasticsearch-oss-6.8.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.0-1
           Available: elasticsearch-oss-6.8.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.1-1
           Available: elasticsearch-oss-7.0.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.0-1
           Available: elasticsearch-oss-7.0.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.1-1
           Available: elasticsearch-oss-7.1.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.0-1
           Available: elasticsearch-oss-7.1.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.1-1
           Available: elasticsearch-oss-7.2.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.2.0-1
Error: Package: opendistro-job-scheduler-1.0.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
           Requires: elasticsearch-oss = 7.0.1
           Installed: elasticsearch-oss-6.7.1-1.noarch (@elasticsearch-6.x)
               elasticsearch-oss = 6.7.1-1
           Available: elasticsearch-oss-6.3.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.0-1
           Available: elasticsearch-oss-6.3.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.1-1
           Available: elasticsearch-oss-6.3.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.2-1
           Available: elasticsearch-oss-6.4.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.0-1
           Available: elasticsearch-oss-6.4.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.1-1
           Available: elasticsearch-oss-6.4.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.2-1
           Available: elasticsearch-oss-6.4.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.3-1
           Available: elasticsearch-oss-6.5.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.0-1
           Available: elasticsearch-oss-6.5.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.1-1
           Available: elasticsearch-oss-6.5.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.2-1
           Available: elasticsearch-oss-6.5.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.3-1
           Available: elasticsearch-oss-6.5.4-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.4-1
           Available: elasticsearch-oss-6.6.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.0-1
           Available: elasticsearch-oss-6.6.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.1-1
           Available: elasticsearch-oss-6.6.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.2-1
           Available: elasticsearch-oss-6.7.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.0-1
           Available: elasticsearch-oss-6.7.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.2-1
           Available: elasticsearch-oss-6.8.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.0-1
           Available: elasticsearch-oss-6.8.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.1-1
           Available: elasticsearch-oss-7.0.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.0-1
           Available: elasticsearch-oss-7.0.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.1-1
           Available: elasticsearch-oss-7.1.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.0-1
           Available: elasticsearch-oss-7.1.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.1-1
           Available: elasticsearch-oss-7.2.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.2.0-1
Error: Package: opendistro-alerting-1.0.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
           Requires: elasticsearch-oss = 7.0.1
           Installed: elasticsearch-oss-6.7.1-1.noarch (@elasticsearch-6.x)
               elasticsearch-oss = 6.7.1-1
           Available: elasticsearch-oss-6.3.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.0-1
           Available: elasticsearch-oss-6.3.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.1-1
           Available: elasticsearch-oss-6.3.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.2-1
           Available: elasticsearch-oss-6.4.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.0-1
           Available: elasticsearch-oss-6.4.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.1-1
           Available: elasticsearch-oss-6.4.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.2-1
           Available: elasticsearch-oss-6.4.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.3-1
           Available: elasticsearch-oss-6.5.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.0-1
           Available: elasticsearch-oss-6.5.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.1-1
           Available: elasticsearch-oss-6.5.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.2-1
           Available: elasticsearch-oss-6.5.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.3-1
           Available: elasticsearch-oss-6.5.4-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.4-1
           Available: elasticsearch-oss-6.6.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.0-1
           Available: elasticsearch-oss-6.6.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.1-1
           Available: elasticsearch-oss-6.6.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.2-1
           Available: elasticsearch-oss-6.7.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.0-1
           Available: elasticsearch-oss-6.7.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.2-1
           Available: elasticsearch-oss-6.8.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.0-1
           Available: elasticsearch-oss-6.8.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.1-1
           Available: elasticsearch-oss-7.0.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.0-1
           Available: elasticsearch-oss-7.0.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.1-1
           Available: elasticsearch-oss-7.1.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.0-1
           Available: elasticsearch-oss-7.1.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.1-1
           Available: elasticsearch-oss-7.2.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.2.0-1
Error: Package: opendistroforelasticsearch-1.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
           Requires: opendistro-security < 1.0.1
           Removing: opendistro-security-0.9.0.0-0.noarch (@opendistroforelasticsearch-artifacts-repo)
               opendistro-security = 0.9.0.0-0
           Updated By: opendistro-security-1.1.0.0-0.noarch (opendistroforelasticsearch-artifacts-repo)
               opendistro-security = 1.1.0.0-0
           Available: opendistro-security-0.7.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
               opendistro-security = 0.7.0.0-1
           Available: opendistro-security-0.7.0.1-1.noarch (opendistroforelasticsearch-artifacts-repo)
               opendistro-security = 0.7.0.1-1
           Available: opendistro-security-0.8.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
               opendistro-security = 0.8.0.0-1
           Available: opendistro-security-1.0.0.0-0.noarch (opendistroforelasticsearch-artifacts-repo)
               opendistro-security = 1.0.0.0-0
Error: Package: opendistroforelasticsearch-1.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
           Requires: elasticsearch-oss = 7.0.1
           Installed: elasticsearch-oss-6.7.1-1.noarch (@elasticsearch-6.x)
               elasticsearch-oss = 6.7.1-1
           Available: elasticsearch-oss-6.3.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.0-1
           Available: elasticsearch-oss-6.3.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.1-1
           Available: elasticsearch-oss-6.3.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.3.2-1
           Available: elasticsearch-oss-6.4.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.0-1
           Available: elasticsearch-oss-6.4.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.1-1
           Available: elasticsearch-oss-6.4.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.2-1
           Available: elasticsearch-oss-6.4.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.4.3-1
           Available: elasticsearch-oss-6.5.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.0-1
           Available: elasticsearch-oss-6.5.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.1-1
           Available: elasticsearch-oss-6.5.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.2-1
           Available: elasticsearch-oss-6.5.3-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.3-1
           Available: elasticsearch-oss-6.5.4-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.5.4-1
           Available: elasticsearch-oss-6.6.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.0-1
           Available: elasticsearch-oss-6.6.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.1-1
           Available: elasticsearch-oss-6.6.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.6.2-1
           Available: elasticsearch-oss-6.7.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.0-1
           Available: elasticsearch-oss-6.7.2-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.7.2-1
           Available: elasticsearch-oss-6.8.0-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.0-1
           Available: elasticsearch-oss-6.8.1-1.noarch (elasticsearch-6.x)
               elasticsearch-oss = 6.8.1-1
           Available: elasticsearch-oss-7.0.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.0-1
           Available: elasticsearch-oss-7.0.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.0.1-1
           Available: elasticsearch-oss-7.1.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.0-1
           Available: elasticsearch-oss-7.1.1-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.1.1-1
           Available: elasticsearch-oss-7.2.0-1.x86_64 (elasticsearch-7.x)
               elasticsearch-oss = 7.2.0-1
Error: Package: opendistroforelasticsearch-1.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
           Requires: opendistro-sql < 1.0.1
           Removing: opendistro-sql-0.9.0.0-1.noarch (@opendistroforelasticsearch-artifacts-repo)
               opendistro-sql = 0.9.0.0-1
           Updated By: opendistro-sql-1.1.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
               opendistro-sql = 1.1.0.0-1
           Available: opendistro-sql-0.7.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
               opendistro-sql = 0.7.0.0-1
           Available: opendistro-sql-0.8.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
               opendistro-sql = 0.8.0.0-1
           Available: opendistro-sql-1.0.0.0-1.noarch (opendistroforelasticsearch-artifacts-repo)
               opendistro-sql = 1.0.0.0-1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
</pre>

**Comment by weicongs-amazon** [comment] 2020-05-26 21:34
close this issue since it's very old one. feel free to reopen it or create a new one if the issue is still there

**Closed by weicongs-amazon** 2020-05-26 21:34 UTC
Labels: bug, build-dependencies
