### ISSUE TITLE
Read-Only filesystem error on master, data and client nodes when setting any config value

### ISSUE THREAD

**Issue by rrichardson** [opendistro-for-elasticsearch/opendistro-build#121] opened 2020-05-01 20:19 UTC
If I set `config:` in values.yaml to anything other than `{}` then the nodes all fail to start, because it appears it is trying to write elasticsearch.yml to a read-only part of the filesystem. 

```
OpenDistro for Elasticsearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/elasticsearch
Elasticsearch install type: rpm/deb on CentOS Linux release 7.7.1908 (Core)
Elasticsearch config dir: /usr/share/elasticsearch/config
Elasticsearch config file: /usr/share/elasticsearch/config/elasticsearch.yml
Elasticsearch bin dir: /usr/share/elasticsearch/bin
Elasticsearch plugins dir: /usr/share/elasticsearch/plugins
Elasticsearch lib dir: /usr/share/elasticsearch/lib
Detected Elasticsearch Version: x-content-7.6.1
Detected Open Distro Security Version: 1.6.0.0

tee: /usr/share/elasticsearch/config/elasticsearch.yml: Read-only file system
```

**Comment by weicongs-amazon** [comment] 2020-05-19 04:52
Hi @rrichardson  could you help to share your config values?

**Comment by drazul** [comment] 2020-05-28 10:34
Hi,
Same error for me.
Reproduce it is easy: you only need to add any value on `elasticsearch.config` map.

I tried with different configurations, I even explicitly  set the writting mode to 644 but it's not working.

My Kubernetes version is `v1.14.10-gke.36` (on GCP)

**Comment by weicongs-amazon** [comment] 2020-06-05 23:20
@rrichardson @drazul have you set up opendistro_security related configurations in the elasticsearch.config map? pls see the note listed in the doc: https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm#notes-about-default-installation 

And we have made an improvement: https://github.com/opendistro-for-elasticsearch/opendistro-build/commit/b93ce34d85645e55c3eafedf5d5ef5e0c8272a07 with latest docker file to have a way to disable this default demo configuration. But this isn't included in any released version yet.

**Comment by weicongs-amazon** [comment] 2020-06-05 23:23
And this is another workaround we can try: https://stackoverflow.com/questions/49614034/kubernetes-deployment-read-only-filesystem-error
Copy the readonly file once to enable the write permission of the elasticsearch.yml

**Comment by weicongs-amazon** [comment] 2020-06-15 14:32
close the issue. feel free to reopen

**Closed by weicongs-amazon** 2020-06-15 14:32 UTC
Labels: helm, pending, question

**Comment by chhaosh** [comment] 2021-01-15 22:00
The problem is, if following https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm#notes-about-default-installation to use default open distro security demo configuration, the elastic config section in values.yaml won't work and so far I did not see a work around to address it before running helm install command

**Comment by ryandawsonuk** [comment] 2021-01-27 18:38
I also hit this when trying to set `elasticsearch.config.thread_pool.write.queue_size`. 

I was looking into the workaround by[ copying to an emptyDir volume](https://stackoverflow.com/questions/49614034/kubernetes-deployment-read-only-filesystem-error) should work. I was working to the steps to this. It requires setting up a volume with extraVolumes, mounting it with extraVolumeMounts, copying with extraInitContainers and then once the data is copied to the emptyDir volume we'd need to tell the chart to use that one. But that [doesn't seem to be configurable](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/opendistro-es/templates/elasticsearch/es-master-sts.yaml#L171). @weicongs-amazon could we reopen this?

**Comment by nugmanovtimur** [comment] 2021-03-01 18:38
@weicongs-amazon we are facing this problem as well, would it be possible to reopen this issue?

**Comment by chhaosh** [comment] 2021-03-01 18:42
> @weicongs-amazon we are facing this problem as well, would it be possible to reopen this issue?

We end up building customized docker image based on original open distro docker image and during build process we first copy in the customized elasticsearch.yml then run /usr/share/elasticsearch/plugins/opendistro_security/tools/install_demo_configuration.sh -y -i -s
at last. Full docker file as below (we also customized internal_user.yml to change default admin/admin credentials)
"
FROM amazon/opendistro-for-elasticsearch:1.9.0
COPY internal_users.yml /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/
COPY elasticsearch.yml /usr/share/elasticsearch/config/
RUN /usr/share/elasticsearch/plugins/opendistro_security/tools/install_demo_configuration.sh -y -i -s

"

**Comment by nugmanovtimur** [comment] 2021-03-02 17:20
@chhaosh thanks a lot, your comment has been most helpful!

However, I had to omit this line to make it work:
`RUN /usr/share/elasticsearch/plugins/opendistro_security/tools/install_demo_configuration.sh -y -i -s`
