### ISSUE TITLE
Upgrading to opendistro from elasticsearch  6.8

### ISSUE THREAD

**Issue by sushovan23** [opendistro-for-elasticsearch/opendistro-build#198] opened 2020-05-28 15:46 UTC
I am trying to upgrade from elasticsearch 6.8 to opendistro 1.6.0
I’m following cluster restart upgrade steps
but after starting elasticsearch when trying to query elastic search for nodes its says
Open Distro Security not initialized.
Then I try to enable security by running the` securityadmin.sh` script
Script is able to connect to cluster but Im getting following error:

```
Elasticsearch Version: 7.6.1
Open Distro Security Version: 1.6.0.0
Diagnostic trace written to: /etc/elasticsearch/securityadmin_diag_trace_2020-May-28_14-36-26.txt
Contacting elasticsearch cluster 'elasticsearch' ...
Clustername:test6x
Clusterstate: RED
Number of nodes: 5
Number of data nodes: 2
.opendistro_security index already exists, so we do not need to create one.
ERR: .opendistro_security index state is RED.
Populate config from /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/
Will update '_doc/config' with /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
   FAIL: Configuration for 'config' failed because of UnavailableShardsException[[.opend
```

Is this a known issue?

**Comment by sushovan23** [comment] 2020-05-28 15:47
not sure how `.opendistro_security` already exists since we were not using opendistro in 6.8

**Comment by weicongs-amazon** [comment] 2020-05-28 21:43
@sushovan23  could you help to share the elasticsearch.yml configuration file and more detailed logs related to the issue "Open Distro Security not initialized."?  And which distribution type are you using for upgrade: rpm, deb, tarball?

**Comment by weicongs-amazon** [comment] 2020-06-05 16:09
close this issue firstly. If the issue is still there, feel free to reopen

**Closed by weicongs-amazon** 2020-06-05 16:09 UTC
Labels: question, upgrade
